version: "3.8"
name: megafon_test

services:
  app:
    build:
      context: .
      dockerfile: python.Dockerfile
    command: python3 main.py
    restart: on-failure
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

